#Should the Server do automatic restarts?
auto_restart = true
#Times in 24 hour format on with the server will automaticaly restarts.
restart_times = ["06:00"]
#Message that is shown on auto restart.
restart_message = "Gaïa va bientôt redémarrer. Merci de vous déconnecter."
#Is the server started by an external restart script?
uses_restart_script = false
#Should the server be automatically restarted when it crashes.
restart_on_crash = true
#Command that is executed on Server stopped to restart the server. Only called if [uses_restart_script] is false.
restart_command = "~/ModServer/modserver/start.bat"

