
[settings]
	#Text used to alert players that someone stopped trying to sleep
	OnWakeText = "a quitté son lit."
	#Allow players to set their spawn point using a bed during the day
	AllowSetSpawnDaytime = true
	#Text used to alert players that someone is trying to sleep
	OnSleepText = "est entrain de dormir."
	#Text to alert the server that sleeping was successful
	OnMorningText = "Un nouveau jour se lève."
	#Players below this Y level will be counted as miners
	#Range: 1 ~ 255
	GroundLevel = 64
	#Enable alerts
	AlertEnabled = true
	#Include miners in player calculations
	IncludeMiners = false
	#Percentage of players required to trigger a successful sleep.
	#Range: 0 ~ 100
	SleeperPerc = 50

